#!/bin/bash
# Generates test439/Core/Inc/aws_credentials.h from PEM files in ~/.secrets/
set -euo pipefail

SECRETS_DIR="$HOME/.secrets"
OUTPUT_FILE="Core/Inc/aws_credentials.h"

CERT_FILE="$SECRETS_DIR/stm32-aws-certificate.pem.crt"
KEY_FILE="$SECRETS_DIR/stm32-aws-private.pem.key"
ROOTCA_FILE="$SECRETS_DIR/AmazonRootCA1.pem"

for f in "$CERT_FILE" "$KEY_FILE" "$ROOTCA_FILE"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: Missing $f" >&2
        echo "See docs/connecting-to-AWS.md for setup instructions." >&2
        exit 1
    fi
done

pem_to_c_array() {
    local file="$1"
    local varname="$2"
    echo "static const char ${varname}[] __attribute__((section(\".rodata\"))) ="
    while IFS= read -r line; do
        printf '    "%s\\n"\n' "$line"
    done < "$file"
    echo "    \"\\0\";"
}

{
    echo "/* Auto-generated by generate_secrets_header.sh. DO NOT EDIT. */"
    echo "#ifndef AWS_CREDENTIALS_H"
    echo "#define AWS_CREDENTIALS_H"
    echo ""
    pem_to_c_array "$CERT_FILE" "device_cert"
    echo ""
    pem_to_c_array "$KEY_FILE" "device_key"
    echo ""
    pem_to_c_array "$ROOTCA_FILE" "root_ca_cert"
    echo ""
    echo "#endif /* AWS_CREDENTIALS_H */"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
