name: Build Custom Image

on:
#  push:
#    paths:
#      - "Dockerfile"
#      - ".github/workflows/build-image.yml"
#  pull_request:
#    branches:
#      - main  # Change this to your default branch if different

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
