name: Gitleaks Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write   # needed for the action to comment on PRs

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # No inputs are required; the action uses the built‑in token automatically.
        # If you want to customise the scan, use the supported inputs (e.g., config, report_format, etc.).
        # Example of a supported input:
        #   with:
        #     config: .gitleaks.toml
