name: Gitleaks Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# The token must have write permission on pull‑requests
permissions:
  contents: read
  pull-requests: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          # Pass the automatically created token
          token: ${{ secrets.GITHUB_TOKEN }}
          args: detect --source . --fail-on-secrets --redact
