name: STM32 Code Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debugging (tmate session)'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    # Use a container with STM32CubeMX preinstalled
    container:
      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    env:
      # Make HOME deterministic and cacheable
      CUBEMX_HOME: ${{ github.workspace }}/.cubemx_home
      HOME: ${{ github.workspace }}/.cubemx_home
      DEBUG: ${{ github.event.inputs.debug }}
      # Bump this if the image upgrades CubeMX (affects cache key)
      CUBEMX_VERSION: "6.15.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify IOC file exists
        run: |
          test -f "${GITHUB_WORKSPACE}/Initial_project.ioc" || {
            echo "::error::Initial_project.ioc not found at ${GITHUB_WORKSPACE}/Initial_project.ioc"
            exit 1
          }

      - name: Prepare CubeMX HOME
        run: |
          mkdir -p "${CUBEMX_HOME}/.stm32cubemx" \
                   "${CUBEMX_HOME}/.stmcufinder" \
                   "${CUBEMX_HOME}/STM32Cube/Repository"
          # Help Java/CubeMX use our HOME consistently
          echo "JAVA
