name: STM32 Code Generation

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  #      - doc/1-plan
  pull_request:
    branches:
      - main  # Change this to your default branch if different

  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      debug:
        description: 'Enable debugging'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ github.event.inputs.debug }}

    container:
      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create generate_script.txt
        shell: bash
        run: |
          echo "load STM32F407xx" > generate_script.txt
          echo "project name Initial_project" >> generate_script.txt
          echo "project toolchain \"Makefile\"" >> generate_script.txt
          echo "project path \"/__w/STM32-AWS/STM32-AWS\"" >> generate_script.txt
          echo "config load \"/__w/STM32-AWS/STM32-AWS/Initial_project.ioc\"" >> generate_script.txt
          echo "project generate" >> generate_script.txt
          echo "exit" >> generate_script.txt
      - run: cat generate_script.txt

      - run: echo $PWD

      - name: Run STM32CubeMX
        timeout-minutes: 3
        run: |
          SCRIPT_PATH="$(realpath "generate_script.txt")"
          echo "Using SCRIPT_PATH=$SCRIPT_PATH"
          echo "Using HOME=$HOME"
          echo "Using PWD=$PWD"
          xvfb-run -a -s "-screen 0 1024x768x24" /opt/STM32CubeMX/STM32CubeMX -q "$SCRIPT_PATH"


      # Install ARM GCC + make
      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi

      # Build (CubeMX Makefile at repo root)
      - name: Build firmware
        working-directory: ${{ github.workspace }}
        env:
          MAKEFLAGS: -j$(nproc)
        run: |
          make all
          arm-none-eabi-size build/*.elf || true

      # (Optional) Upload build outputs
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/**/*.elf
            build/**/*.bin
            build/**/*.hex
            build/**/*.map


      - name: Setup tmate session for debugging
        if: env.DEBUG == 'true'
        # if: always()
        uses: mxschmitt/action-tmate@v3