name: STM32 Code Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug:
        description: Enable debugging
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ github.event.inputs.debug }}

    container:
      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Prepare a HOME inside the repo workspace so CubeMX writes there
      - name: Set HOME for CubeMX
        shell: bash
        run: |
          echo "HOME=${GITHUB_WORKSPACE}/.cubemx_home" >> "$GITHUB_ENV"
          echo "JAVA_TOOL_OPTIONS=-Duser.home=${GITHUB_WORKSPACE}/.cubemx_home" >> "$GITHUB_ENV"
          mkdir -p "${GITHUB_WORKSPACE}/.cubemx_home/.stm32cubemx" \
                   "${GITHUB_WORKSPACE}/.cubemx_home/.stmcufinder" \
                   "${GITHUB_WORKSPACE}/.cubemx_home/STM32Cube/Repository"

      - name: Show env after HOME export
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "HOME=$HOME (this step still shows old HOME; next steps use the new one)"
          echo "JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"

      # Cache CubeMX data so subsequent runs are fast and quiet
      - name: Cache CubeMX data
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cubemx_home/.stm32cubemx
            ${{ github.workspace }}/.cubemx_home/.stmcufinder
            ${{ github.workspace }}/.cubemx_home/STM32Cube/Repository
          key: cubemx-${{ runner.os }}-6.15.0-${{ hashFiles('**/*.ioc') }}
          restore-keys: |
            cubemx-${{ runner.os }}-6.15.0-
            cubemx-${{ runner.os }}-

      - name: Create generate_script.txt
        shell: bash
        run: |
          {
            echo "config load \"${GITHUB_WORKSPACE}/Initial_project.ioc\""
            echo "generate code \"${GITHUB_WORKSPACE}\""
            echo "exit"
          } > generate_script.txt
          cat generate_script.txt

      - name: Show CubeMX install
        run: ls -la /opt/STM32CubeMX/

      - name: Run STM32CubeMX (headless)
        env:
          HOME: ${{ github.workspace }}/.c
