name: STM32 Code Generation

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different

  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      debug:
        description: 'Enable debugging'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ github.event.inputs.debug }}

    container:
#      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:dev
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create generate_script.txt
        shell: bash
        env:
          ST_CUBE_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          ST_CUBE_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
        run: |
          echo "login \"${ST_CUBE_EMAIL}\" \"${ST_CUBE_PASSWORD}\" y" > generate_script.txt
          echo "swmgr refresh" >> generate_script.txt
          echo "swmgr install stm32cube_f4_1.28.2 ask" >> generate_script.txt
          echo "config load \"/__w/STM32-AWS/STM32-AWS/Initial_project.ioc\"" >> generate_script.txt
          echo "project toolchain \"Makefile\"" >> generate_script.txt
          echo "project path \"/__w/STM32-AWS/STM32-AWS\"" >> generate_script.txt
          echo "project name \"Initial_project\"" >> generate_script.txt
          echo "project generateunderroot 1" >> generate_script.txt
          echo "project generate" >> generate_script.txt
          echo "exit" >> generate_script.txt
      - run: cat generate_script.txt

      - run: echo $PWD

      - name: Run STM32CubeMX
#        continue-on-error: true
        id: generate
        timeout-minutes: 5
        run: |
          SCRIPT_PATH="$(realpath "generate_script.txt")"
          echo "Using SCRIPT_PATH=$SCRIPT_PATH"
          echo "Using HOME=$HOME"
          echo "Using PWD=$PWD"
          xvfb-run -a -s "-screen 0 1024x768x24" /opt/STM32CubeMX/STM32CubeMX -q "$SCRIPT_PATH"


      # Install ARM GCC + make
      - name: Install ARM GCC toolchain
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi \
            libnewlib-arm-none-eabi \
            make

      # Build (CubeMX Makefile at repo root)
      - name: Build firmware
        id: build
        if: steps.generate.outcome == 'success'
        working-directory: /__w/STM32-AWS/STM32-AWS/Initial_project
#        continue-on-error: true
        env:
          MAKEFLAGS: -j$(nproc)
        run: |
          make
          arm-none-eabi-size build/*.elf || true

      # 1) Verify artifacts exist
      - name: Check build artifacts
        working-directory: /__w/STM32-AWS/STM32-AWS/Initial_project
        run: |
          ls -la build || ls -la .
          ELF=$(ls build/*.elf 2>/dev/null || ls *.elf)
          BIN=$(ls build/*.bin 2>/dev/null || ls *.bin)
          MAP=$(ls build/*.map 2>/dev/null || ls *.map)
          echo "ELF=$ELF BIN=$BIN MAP=$MAP"
          test -f "$ELF" && test -f "$BIN" && test -f "$MAP"

      # 2) Show size and enforce flash/RAM budgets (STM32F407: ~1MB Flash, 192KB RAM)
      - name: Enforce size budgets
        working-directory: /__w/STM32-AWS/STM32-AWS/Initial_project
        shell: bash
        run: |
          set -euo pipefail
          ELF=$(ls build/*.elf 2>/dev/null || ls *.elf)
          # parse the last line of `size` output
          read -r TEXT DATA BSS DEC <<<"$(arm-none-eabi-size "$ELF" | awk 'END{print $1,$2,$3,$4}')"
          arm-none-eabi-size "$ELF"
          FLASH_USED=$((TEXT+DATA))
          RAM_USED=$((DATA+BSS))
          echo "FLASH_USED=$FLASH_USED  RAM_USED=$RAM_USED"
          [ "$FLASH_USED" -le $((1024*1024)) ] || { echo "Flash overflow"; exit 1; }
          [ "$RAM_USED"   -le $((192*1024))   ] || { echo "RAM overflow"; exit 1; }

      # 3) Basic ELF sanity: vector table & entry symbol present
      - name: Check ELF sanity
        working-directory: /__w/STM32-AWS/STM32-AWS/Initial_project
        run: |
          ELF=$(ls build/*.elf 2>/dev/null || ls *.elf)
          # Ensure Reset_Handler exists
          arm-none-eabi-nm "$ELF" | grep -q ' T Reset_Handler' || { echo "Missing Reset_Handler"; exit 0; }
          # Dump first few vectors for debugging
          arm-none-eabi-objdump -D -j .isr_vector "$ELF" | head -n 40

      # (Optional) Upload build outputs
      - name: Upload firmware artifacts
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          retention-days: 3
          path: |
            /__w/STM32-AWS/STM32-AWS/Initial_project/build/**/*.elf
            /__w/STM32-AWS/STM32-AWS/Initial_project/build/**/*.bin
            /__w/STM32-AWS/STM32-AWS/Initial_project/build/**/*.hex
            /__w/STM32-AWS/STM32-AWS/Initial_project/build/**/*.map

      - name: Print workflow status
        if: always() && env.DEBUG == 'true'
        run: |
          if [ "${{ job.status }}" = "failure" ]; then
            echo "A previous step failed. Entering tmate debug session."
          else
            echo "Workflow succeeded. Entering tmate debug session."
          fi

      - name: Setup tmate session for debugging
        if: always() && env.DEBUG == 'true'
        uses: mxschmitt/action-tmate@v3