name: STM32 Code Generation

on:
  push:
    branches:
      - main  # Change this to your default branch if different
#      - doc/1-plan
  pull_request:
    branches:
      - main  # Change this to your default branch if different

  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      debug:
        description: 'Enable debugging'
        required: false
        default: 'false'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ github.event.inputs.debug }}
      # HOME: ${GITHUB_WORKSPACE}/.cubemx_home
      # JAVA_TOOL_OPTIONS: -Duser.home=${GITHUB_WORKSPACE}/.cubemx_home

    container:
      image: ghcr.io/torchikaii/stm32-aws/cubemx-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
       # Set HOME under the container's workspace and persist it
      - name: Set HOME for CubeMX
        run: |
          echo "HOME=$GITHUB_WORKSPACE/.cubemx_home" >> "$GITHUB_ENV"
          echo "JAVA_TOOL_OPTIONS=-Duser.home=$GITHUB_WORKSPACE/.cubemx_home" >> "$GITHUB_ENV"
          mkdir -p "$GITHUB_WORKSPACE/.cubemx_home/.stm32cubemx" \
                   "$GITHUB_WORKSPACE/.cubemx_home/.stmcufinder" \
                   "$GITHUB_WORKSPACE/.cubemx_home/STM32Cube/Repository"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "HOME will be $HOME (next step)"
          
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.HOME }}/.stm32cubemx
            ${{ env.HOME }}/.stmcufinder
            ${{ env.HOME }}/STM32Cube/Repository
          key: cubemx-${{ runner.os }}-6.15.0-${{ hashFiles('**/*.ioc') }}
          restore-keys: |
            cubemx-${{ runner.os }}-6.15.0-
            cubemx-${{ runner.os }}-
            
      - name: Create generate_script.txt
        shell: bash
        run: |
          echo "config load \"${GITHUB_WORKSPACE}/Initial_project.ioc\"" > generate_script.txt
          echo "generate code \"${GITHUB_WORKSPACE}\"" >> generate_script.txt
          echo "exit" >> generate_script.txt

      - run: cat generate_script.txt
      - run: ls -la /opt/STM32CubeMX/
        
      
      - name: Ensure dirs exist
        run: |
          mkdir -p "$HOME/.stm32cubemx" "$HOME/.stmcufinder" "$HOME/STM32Cube/Repository"

      - name: Run STM32CubeMX
        env:
          JAVA_TOOL_OPTIONS: -Duser.home=${{ env.HOME }}  # optional, but explicit
        timeout-minutes: 20
        run: |
          echo "JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
          echo "HOME=$HOME"
          SCRIPT_PATH="$(realpath "$GITHUB_WORKSPACE/generate_script.txt")"
          echo "Using SCRIPT_PATH=$SCRIPT_PATH"
          xvfb-run -a -s "-screen 0 1024x768x24" /opt/STM32CubeMX/STM32CubeMX -q "$SCRIPT_PATH"
        
      - name: Build firmware
        working-directory: .
        run: |
          echo $PWD
          ls -la
          test -f Makefile || { echo "No Makefile. Set Toolchain/IDE=Makefile in the .ioc and regenerate."; exit 1; }
          make -j"$(nproc)" all
          make hex || true
          make bin || true
          make size || true  
          
      # Optional: upload logs for debugging
      # - name: Upload CubeMX logs
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cubemx-logs
      #     path: |
      #       .cubemx_home/.stm32cubemx/**
      #       .cubemx_home/.stmcufinder/**
     
      - name: Setup tmate session for debugging
        if: env.DEBUG == 'true'
        # if: always()
        uses: mxschmitt/action-tmate@v3
        
